### ISSUE TITLE
inconsistency of Fashion-MNIST results using resnet 20

### ISSUE THREAD

**Issue by WayneDW** [zhunzhong07/Random-Erasing#10]
I ran your code several times on the dataset Fashion-MNIST using resnet20 with random erasing 0.5.

I didn't get your reported error 4.02% ± 0.07 using your default code "python fashionmnist.py --dataset fashionmnist --arch resnet --depth 20 --p 0.5", the results are roughly 4.5% on average.

Could you show me how can I get the result ~96% as you mentioned in your paper?

Thanks a lot.

**Comment by WayneDW** [comment]
Never mind, you mentioned this problem before.

I wonder if your CIFAR 10 results are as what you reported in your paper?

Please update your arXiv paper to reflect the true Fashion-MNIST accuracy. 

Thanks a lot for your code.

**Comment by WayneDW** [comment]
Never mind, you mentioned this problem before.

Thanks a lot for your clear code.

Please update your arXiv paper to reflect the new Fashion-MNIST accuracy.

**Comment by WayneDW** [comment]
I tested your resnet20 on Fashion MNIST dataset, the errors are 4.45%±0.04% (with random erasing) vs 4.82%±0.04%, this shows random erasing is indeed very powerful.

**Comment by zhunzhong07** [comment]
I am glad to see random erasing is work for you.
