### ISSUE TITLE
RE-R in the paper

### ISSUE THREAD

**Issue by yu4u** [zhunzhong07/Random-Erasing#2]
Simple but effective, very interesting work!
I wonder to which methods `RE-R: erasing with random values` corresponds; (1) region level randomization or (2) pixel level randomization.

(1) `img[2, x1:x1+h, y1:y1+w] = random.uniform(0, 1)`
(2) `img[:, x1:x1+h, y1:y1+w] = torch.from_numpy(np.random.rand(3, h, w))`

Did you compare the two of them?

**Comment by zhunzhong07** [comment]
the second one is the RE-R in our paper. But these two types of values would achieve similar performance, you can try it.

**Comment by yu4u** [comment]
Thank you for your reply!
I already tested both of them, and I think pixel level randomization seems to be slightly better.
https://github.com/yu4u/cutout-random-erasing
