### ISSUE TITLE
实现与论文叙述不一致

### ISSUE THREAD

**Issue by mashuiping** [zhunzhong07/Random-Erasing#6]
## 看到您写的代码跟RandomResizeCrop很像，同时您的论文Algorithm 1中提到re = Rand(r1, r2), 可是实现代码中（transfrom.py）并没有r2，而是直接取了r1的倒数作为r2，RandomResizeCrop是上下限都可以设置的，想问一下，是不是有其他考虑？

**Comment by zhunzhong07** [comment]
Please refer to our experiment setting in Section 5.1.2. We set r1=1/r2. If you want to set r1 and r2 with any value, you could modify our code. In our experiment, we find that it can achieve appropriate improvement when setting r1=1/r2=0.3.
